namespace OpenKneeboardApp
{
    [default_interface]
    runtimeclass AdvancedSettingsPage: Microsoft.UI.Xaml.Controls.Page,
                                       Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        AdvancedSettingsPage();

        Boolean DualKneeboards;
        Boolean GazeInputFocus;

        Boolean LoopPages;
        Boolean LoopTabs;

        Boolean MultipleProfiles;

		UInt32 MinimumPenRadius;
		UInt32 MinimumEraseRadius;
		UInt32 PenSensitivity;
		UInt32 EraseSensitivity;

        Boolean Quirk_OculusSDK_DiscardDepthInformation;
        Boolean Quirk_Varjo_OpenXR_D3D12_DoubleBuffer;

        Boolean CanChangeElevation { get; };
        Int32 DesiredElevation;
    }
}
