namespace OpenKneeboardApp
{
    [default_interface]
    runtimeclass AdvancedSettingsPage: Microsoft.UI.Xaml.Controls.Page,
                                       Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        AdvancedSettingsPage();

        Boolean GazeInputFocus;

        Boolean MultipleProfiles;

        Boolean Bookmarks;

        Boolean EnableMouseButtonBindings;

        UInt8 AppWindowViewMode;

        Boolean LoopPages;
        Boolean LoopTabs;
        Boolean LoopProfiles;
        Boolean LoopBookmarks;

        Boolean InGameHeader;
        Boolean InGameFooter;
        Boolean InGameFooterFrameCount;

        Boolean TintEnabled;
        Single TintBrightness;
        Windows.UI.Color Tint;

		UInt32 MinimumPenRadius;
		UInt32 MinimumEraseRadius;
		UInt32 PenSensitivity;
		UInt32 EraseSensitivity;

        Single TextPageFontSize;

        UInt8 Quirk_OpenXR_Upscaling;
    }
}
