namespace OpenKneeboardApp
{
    [default_interface]
    runtimeclass AppWindowViewModeDialog: Microsoft.UI.Xaml.Controls.ContentDialog
    {
        AppWindowViewModeDialog();
        UInt8 SelectedMode(Microsoft.UI.Xaml.Controls.ContentDialogResult dialogResult);
    }
}
