namespace OpenKneeboardApp
{
    [default_interface]
    runtimeclass GamesSettingsPage: Microsoft.UI.Xaml.Controls.Page,
                                   Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        GamesSettingsPage();
        Windows.Foundation.Collections.IVector<IInspectable> Games { get; };
    }

    [default_interface]
    unsealed runtimeclass GameInstanceUIData : Microsoft.UI.Xaml.Data.ICustomPropertyProvider
    {
        GameInstanceUIData();
        Microsoft.UI.Xaml.Media.Imaging.BitmapSource Icon;
        UInt64 InstanceID;
        String Name;
        String Path;
        UInt8 OverlayAPI;
    }

    [default_interface]
    runtimeclass DCSWorldInstanceUIData : GameInstanceUIData
    {
        DCSWorldInstanceUIData();
        String SavedGamesPath;
    }

    [default_interface]
    runtimeclass GameInstanceUIDataTemplateSelector : Microsoft.UI.Xaml.Controls.DataTemplateSelector {
        GameInstanceUIDataTemplateSelector();
        Microsoft.UI.Xaml.DataTemplate GenericGame;
        Microsoft.UI.Xaml.DataTemplate DCSWorld;
    }
}
