namespace OpenKneeboardApp
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        Microsoft.UI.Xaml.Controls.Frame Frame { get; };
    }
}
