namespace OpenKneeboardApp
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window,
                              Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        MainWindow();
        
        Microsoft.UI.Xaml.Controls.Frame Frame { get; };

        Windows.Foundation.Collections.IVector<IInspectable> NavigationItems { get; };
    }
}
