namespace OpenKneeboardApp
{
    [default_interface]
    runtimeclass NonVRSettingsPage: Microsoft.UI.Xaml.Controls.Page, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        NonVRSettingsPage();

        UInt8 KneeboardHeightPercent;
        UInt32 KneeboardPaddingPixels;
        Single KneeboardOpacity;

        UInt8 KneeboardHorizontalPlacement;
        UInt8 KneeboardVerticalPlacement;
    }

}
