namespace OpenKneeboardApp
{
    [default_interface]
    runtimeclass OKBDeveloperToolsPage: Microsoft.UI.Xaml.Controls.Page
    {
        OKBDeveloperToolsPage();

        Boolean PluginFileTypeInHKCU;

        String AutoUpdateFakeCurrentVersion;
    }
}
