namespace OpenKneeboardApp
{
    [default_interface]
    runtimeclass ProfilesPage: Microsoft.UI.Xaml.Controls.Page
    {
        ProfilesPage();
    }

    [default_interface]
    unsealed runtimeclass ProfileUIData
    {
        ProfileUIData();
        Guid ID;
        String Name;
        Boolean CanDelete;
    }
}
