namespace OpenKneeboardApp
{
    [default_interface]
    runtimeclass RenameTabDialog: Microsoft.UI.Xaml.Controls.ContentDialog
    {
        RenameTabDialog();
        String TabTitle;
    }
}
