namespace OpenKneeboardApp
{
    [default_interface]
    runtimeclass SettingsPage: Microsoft.UI.Xaml.Controls.Page
    {
        SettingsPage();
    }

    [default_interface]
    [contentproperty("Description")]
    runtimeclass SettingsSubpageData
    {
        SettingsSubpageData();
        String Glyph;
        String Title;
        String Description;
    }
}
