namespace OpenKneeboardApp
{
    [default_interface]
    runtimeclass SettingsPage: Microsoft.UI.Xaml.Controls.Page
    {
        SettingsPage();
    }

    enum SettingsSubpageID {
        Games,
        Tabs,
        Input,
        VRConfig,
        NonVRConfig,
    };

    [default_interface]
    [contentproperty("Description")]
    runtimeclass SettingsSubpageData
    {
        SettingsSubpageData();
        SettingsSubpageID ID;
        String Glyph;
        String Title;
        String Description;
    }
}
