namespace OpenKneeboardApp
{
    [default_interface]
    runtimeclass TabSettingsPage: Microsoft.UI.Xaml.Controls.Page
    {
        TabSettingsPage();
    }

    [default_interface]
    unsealed runtimeclass TabUIData
    {
        TabUIData();
        UInt64 InstanceID;
        String Title;
    }

    [default_interface]
    runtimeclass DCSRadioLogTabUIData : TabUIData
    {
        DCSRadioLogTabUIData();
        UInt8 MissionStartBehavior;
    }

    [default_interface]
    runtimeclass TabUIDataTemplateSelector : Microsoft.UI.Xaml.Controls.DataTemplateSelector {
        TabUIDataTemplateSelector();
        Microsoft.UI.Xaml.DataTemplate Generic;
        Microsoft.UI.Xaml.DataTemplate DCSRadioLog;
    }
}
