namespace OpenKneeboardApp {
[default_interface] runtimeclass TabsSettingsPage
  : Microsoft.UI.Xaml.Controls.Page,
  Microsoft.UI.Xaml.Data.INotifyPropertyChanged {
  TabsSettingsPage();
  Windows.Foundation.Collections.IVector<IInspectable> Tabs { get; };
}

[default_interface] unsealed runtimeclass TabUIData
  : Microsoft.UI.Xaml.Data.INotifyPropertyChanged {
  TabUIData();
  UInt64 InstanceID;
  String Title;
  Boolean HasDebugInformation { get; };
  String DebugInformation { get; };
}

[default_interface] runtimeclass DCSRadioLogTabUIData : TabUIData {
  DCSRadioLogTabUIData();
  UInt8 MissionStartBehavior;
  Boolean TimestampsEnabled;
}

[default_interface] runtimeclass WindowCaptureTabUIData : TabUIData {
  WindowCaptureTabUIData();
  String WindowTitle; 
  String ExecutablePathPattern;
  String WindowClass;
  Boolean MatchWindowClass;
  Boolean IsInputEnabled;
  UInt8 MatchWindowTitle;
  Boolean IsCursorCaptureEnabled;
  Boolean CaptureClientArea;
}

[default_interface] runtimeclass BrowserTabUIData: TabUIData {
  BrowserTabUIData();
  Boolean AreOpenKneeboardAPIsEnabled;
  Boolean IsSimHubIntegrationEnabled;
  Boolean IsBackgroundTransparent;
}

[default_interface] runtimeclass TabUIDataTemplateSelector
  : Microsoft.UI.Xaml.Controls.DataTemplateSelector {
  TabUIDataTemplateSelector();
  Microsoft.UI.Xaml.DataTemplate Generic;
  Microsoft.UI.Xaml.DataTemplate Browser;
  Microsoft.UI.Xaml.DataTemplate DCSRadioLog;
  Microsoft.UI.Xaml.DataTemplate WindowCapture;
}
}// namespace OpenKneeboardApp
