namespace OpenKneeboardApp
{
    [default_interface]
    runtimeclass TabSettingsPage: Microsoft.UI.Xaml.Controls.Page
    {
        TabSettingsPage();
    }

    [default_interface]
    runtimeclass TabUIData
    {
        TabUIData();
        UInt64 UniqueID;
        String Title;
    }
}
