namespace OpenKneeboardApp
{
    [default_interface]
    runtimeclass VRSettingsPage: Microsoft.UI.Xaml.Controls.Page, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        VRSettingsPage();

        Boolean SteamVREnabled;
        Boolean OpenXREnabled;
    }
}
