namespace OpenKneeboardApp
{
    [default_interface]
    runtimeclass VRSettingsPage: Microsoft.UI.Xaml.Controls.Page, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        VRSettingsPage();

        Boolean SteamVREnabled;
        Boolean OpenXR64Enabled;
        Boolean OpenXR32Enabled;
    }
}
