import "UIDataItem.idl";

namespace OpenKneeboardApp
{
    [default_interface]
    runtimeclass IndependentVRViewUIKind : UIDataItem {
        IndependentVRViewUIKind();
    }

    [default_interface]
    runtimeclass HorizontalMirrorVRViewUIKind : UIDataItem {
        HorizontalMirrorVRViewUIKind();

        Guid MirrorOf;
    }
}