namespace OpenKneeboardApp
{
    [default_interface]
    runtimeclass VRViewSettingsControl: Microsoft.UI.Xaml.Controls.UserControl, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        VRViewSettingsControl();

        Guid ViewID;
        
        Boolean IsEnabledInVR;

        IInspectable SelectedKind;

        IInspectable SelectedDefaultTab;

        Microsoft.UI.Xaml.Visibility TooManyViewsVisibility { get; };
    }
}
