#include "okEvents.h"

wxDEFINE_EVENT(okEVT_PREVIOUS_TAB, wxCommandEvent);
wxDEFINE_EVENT(okEVT_NEXT_TAB, wxCommandEvent);
wxDEFINE_EVENT(okEVT_PREVIOUS_PAGE, wxCommandEvent);
wxDEFINE_EVENT(okEVT_NEXT_PAGE, wxCommandEvent);

wxDEFINE_EVENT(okEVT_TAB_PIXELS_CHANGED, wxCommandEvent);

wxDEFINE_EVENT(okEVT_TAB_FULLY_REPLACED, wxCommandEvent);
wxDEFINE_EVENT(okEVT_TAB_PAGE_MODIFIED, wxCommandEvent);
wxDEFINE_EVENT(okEVT_TAB_PAGE_APPENDED, wxCommandEvent);

wxDEFINE_EVENT(okEVT_SETTINGS_CHANGED, wxCommandEvent);
wxDEFINE_EVENT(okEVT_GAME_CHANGED, wxCommandEvent);
