source "https://rubygems.org"
gem "jekyll"
gem "json"
gem "jemoji"

gem "just-the-docs"

# Intentionally not in `:jekyll_plugins` because it disables the `_plugins` directory
gem "github-pages"


gem "webrick", group: :development
