source "https://rubygems.org"
gem "github-pages", group: :jekyll_plugins
gem "jekyll"
gem "json"
gem "just-the-docs", git: 'https://github.com/just-the-docs/just-the-docs.git', ref: 'a4e4e312aa3e3f41344e351bb1324ec462911515'

gem "webrick", group: :development
