if("$ENV{GITHUB_REF_TYPE}" STREQUAL "tag")
  set(MATCHING_TAG $ENV{GITHUB_REF_NAME})
else()
  set(MATCHING_TAG NOTFOUND)
endif()

if(DEFINED ENV{GITHUB_RUN_NUMBER})
  set(IS_GITHUB_ACTIONS_BUILD "true")
  set(BUILD_TYPE "gha")
else()
  set(IS_GITHUB_ACTIONS_BUILD "false")
  set(BUILD_TYPE "local")
endif()

set(IS_TAGGED_VERSION false)

if(MATCHING_TAG)
  set(RELEASE_NAME "${MATCHING_TAG}+${BUILD_TYPE}.${VERSION_BUILD}")
  set(IS_TAGGED_VERSION true)
elseif(IS_GITHUB_ACTIONS_BUILD)
  set(RELEASE_NAME "v${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}+${BUILD_TYPE}.${VERSION_BUILD}")
else()
  set(RELEASE_NAME "v${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}+${BUILD_TYPE}")
endif()

if(
  IS_TAGGED_VERSION STREQUAL "true"
  AND IS_GITHUB_ACTIONS_BUILD
  AND NOT "${RELEASE_NAME}" MATCHES "-")
  set(IS_STABLE_RELEASE true)
else()
  set(IS_STABLE_RELEASE false)
endif()

if(INPUT_CPP_FILE)
  configure_file(
    ${INPUT_CPP_FILE}
    ${OUTPUT_CPP_FILE}
    @ONLY
  )
endif()

if(INPUT_RC_FILE)
  configure_file(
    ${INPUT_RC_FILE}
    ${OUTPUT_RC_FILE}
    @ONLY
  )
endif()
